run:
  go: "1.20"
  timeout: 5m
  skip-dirs:
    - '_examples'
    - '_playground'
    - 'adapter/nop'
  allow-parallel-runners: true
  modules-download-mode: 'readonly'

linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
    - forbidigo
    - tagliatelle
    - misspell
    - depguard
linters-settings:
  forbidigo:
    forbid:
      - 'ioutil\.*'
  tagliatelle:
    case:
      use-field-name: false
      rules:
        yaml: snake
        json: snake
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use stdlib instead"
